Xapian::RSet
Xapian::Internal::intrusive_ptr<Internal> Xapian::RSet::internal
Xapian::RSet::RSet(const RSet &rset)
Copy constructor.
void Xapian::RSet::operator=(const RSet &rset)
Assignment operator.
Xapian::RSet::RSet()
Default constructor.
Xapian::RSet::~RSet()
Destructor.
Xapian::doccount Xapian::RSet::size() const
The number of documents in this R-Set.
bool Xapian::RSet::empty() const
Test if this R-Set is empty.
void Xapian::RSet::add_document(Xapian::docid did)
Add a document to the relevance set.
void Xapian::RSet::add_document(const Xapian::MSetIterator &i)
Add a document to the relevance set.
References add_document.
Referenced by add_document.
void Xapian::RSet::remove_document(Xapian::docid did)
Remove a document from the relevance set.
void Xapian::RSet::remove_document(const Xapian::MSetIterator &i)
Remove a document from the relevance set.
References remove_document.
Referenced by remove_document.
bool Xapian::RSet::contains(Xapian::docid did) const
Test if a given document in the relevance set.
bool Xapian::RSet::contains(const Xapian::MSetIterator &i) const
Test if a given document in the relevance set.
References contains.
Referenced by contains.
std::string Xapian::RSet::get_description() const
Return a string describing this object.